### ISSUE TITLE
error results

### ISSUE THREAD

**Issue by summerwbb** [3d-hand-shape/hand-graph-cnn#32]
![image](https://user-images.githubusercontent.com/40291885/76155610-2cb78700-6129-11ea-9e00-4357ac184f5e.png)
I run 'python eval_script.py --config-file "configs/eval_real_world_testset.yaml"', and get this results, what is wrong with me ?

**Comment by 3d-hand-shape** [comment]
We released the code and datasets only for research use. Our released code and datasets cannot be used for any commercial purpose.

Since the pose and mesh are totally wrong on your testing data, we suggest you carefully check the code and the input data you used. Some possible reasons are image format, image resolution, hand detection, etc.
